import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import type { Metadata } from "next";
import Script from "next/script";
import Head from "./head";
import { GlobalProvider } from "./globalProvider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <GlobalProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </GlobalProvider>

        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></Script>
        <script src="https://kit.fontawesome.com/706b455fee.js"></script>
      </body>
    </html>
  );
}
